### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kotowick** [jhund/filterrific_demo#3]
I want to use [Sourcegraph](https://sourcegraph.com) for filterrific_demo code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/jhund/filterrific_demo. (It should only take 30 seconds.)

Thank you!

**Comment by jhund** [comment]
@kotowick I enabled sourcegraph for this repo. I also threw in filterrific for good measure:

* https://sourcegraph.com/github.com/jhund/filterrific_demo
* https://sourcegraph.com/github.com/jhund/filterrific
